# Generated by Django 4.0.2 on 2022-12-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_wallet_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='peticion',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
