# Generated by Django 4.1.2 on 2022-12-02 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile'),
        ('account', '0004_wallet_peticion'),
    ]

    operations = [
    ]
