# Generated by Django 4.1.2 on 2022-10-24 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pixelsaurapp', '0002_alter_categoria_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='id_categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pixelsaurapp.categoria'),
        ),
    ]
