# Generated by Django 4.1.2 on 2022-10-27 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixelsaurapp', '0006_delete_coupon_delete_downloadinstance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenido',
            name='id_categoria',
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='usuario_author',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='contenido',
        ),
    ]
