# Generated by Django 4.1.2 on 2022-10-27 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pixelsaurapp', '0007_remove_contenido_id_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la categoria', max_length=100)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Entra el nombre de tu producto', max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('descripcion', models.TextField(help_text='Entra una descripcion del contenido', max_length=1000)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, default=99.99, max_digits=100, null=True)),
                ('media_banner', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('promocion', models.DecimalField(blank=True, decimal_places=2, default=99.99, max_digits=10, null=True)),
                ('available', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField(auto_now_add=True, null=True)),
                ('fecha_edicion', models.DateField(auto_now=True, null=True)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='pixelsaurapp.categoria')),
                ('usuario_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'index_together': {('id', 'slug')},
            },
        ),
    ]
