# Generated by Django 4.1.2 on 2022-10-27 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixelsaurapp', '0008_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='contenido',
            index_together=None,
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='id_categoria',
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='usuario_author',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='contenido',
        ),
    ]
