# Generated by Django 4.1.2 on 2022-10-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelsaurapp', '0011_alter_categoria_options_alter_categoria_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='media_banner',
            field=models.ImageField(blank=True, null=True, upload_to='contenidos/%Y/%m/%d'),
        ),
    ]
