# Generated by Django 4.1.2 on 2022-10-27 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixelsaurapp', '0012_alter_contenido_media_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenido',
            options={'ordering': ('name',)},
        ),
    ]
