# Generated by Django 4.1.2 on 2022-10-27 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixelsaurapp', '0013_alter_contenido_options'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='contenido',
            index_together=None,
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='id_categoria',
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='usuario_author',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Contenido',
        ),
    ]
