# Generated by Django 4.0.2 on 2022-11-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelsaurapp', '0018_remove_product_usuario_author_product_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='archive',
            field=models.FileField(blank=True, null=True, upload_to='contenidos/%Y/%m/%d'),
        ),
    ]
