# Generated by Django 4.0.2 on 2022-11-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelsaurapp', '0020_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='rating',
            field=models.FloatField(default=3.0),
        ),
    ]
