# Generated by Django 4.0.2 on 2022-11-25 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pixelsaurapp', '0023_regalo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regalo',
            name='desc_cod',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='regalo',
            name='user_rece',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regalo',
            name='user_send',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
