# Generated by Django 4.0.2 on 2022-11-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelsaurapp', '0024_alter_regalo_desc_cod_alter_regalo_user_rece_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regalo',
            name='dedicatoria',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='regalo',
            name='user_rece',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
