# Generated by Django 4.0.2 on 2022-11-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelsaurapp', '0025_regalo_dedicatoria_alter_regalo_user_rece'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='date_rating',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
