# Generated by Django 4.0.2 on 2022-11-26 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixelsaurapp', '0026_calificacion_date_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calificacion',
            old_name='created_by',
            new_name='created_by_id',
        ),
    ]
