# Generated by Django 4.0.2 on 2022-11-26 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixelsaurapp', '0027_rename_created_by_calificacion_created_by_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calificacion',
            old_name='created_by_id',
            new_name='created_by',
        ),
    ]
