# Generated by Django 4.0.2 on 2022-11-26 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixelsaurapp', '0028_rename_created_by_id_calificacion_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacion',
            name='created_by',
        ),
    ]
