# Generated by Django 4.0.2 on 2022-11-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelsaurapp', '0032_calificacion_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='n_descarga',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pos_descarga',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pos_valoracion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='val_promedio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
