# Generated by Django 4.0.2 on 2022-11-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelsaurapp', '0033_product_n_descarga_product_pos_descarga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='n_descarga',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='pos_descarga',
            field=models.IntegerField(blank=True, default=9999),
        ),
        migrations.AlterField(
            model_name='product',
            name='pos_valoracion',
            field=models.IntegerField(blank=True, default=9999),
        ),
        migrations.AlterField(
            model_name='product',
            name='val_promedio',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
