# Generated by Django 4.1.2 on 2022-10-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(default='slug-field')),
                ('description', models.TextField(default=None)),
                ('price', models.DecimalField(decimal_places=2, default=99.99, max_digits=100)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, default=99.99, max_digits=100, null=True)),
            ],
        ),
    ]
