# Generated by Django 4.0.2 on 2022-11-21 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pixelsaurapp', '0018_remove_product_usuario_author_product_usuario'),
        ('my_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mybuyedproducts',
            options={},
        ),
        migrations.AlterIndexTogether(
            name='mybuyedproducts',
            index_together=set(),
        ),
        migrations.AddField(
            model_name='mybuyedproducts',
            name='producto_comprado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pixelsaurapp.product'),
        ),
        migrations.RemoveField(
            model_name='mybuyedproducts',
            name='category',
        ),
        migrations.RemoveField(
            model_name='mybuyedproducts',
            name='created',
        ),
        migrations.RemoveField(
            model_name='mybuyedproducts',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mybuyedproducts',
            name='image',
        ),
        migrations.RemoveField(
            model_name='mybuyedproducts',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mybuyedproducts',
            name='ordenid',
        ),
        migrations.RemoveField(
            model_name='mybuyedproducts',
            name='price',
        ),
        migrations.RemoveField(
            model_name='mybuyedproducts',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='mybuyedproducts',
            name='valid_download',
        ),
    ]
