# Generated by Django 4.0.2 on 2022-12-01 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pixelsaurapp', '0034_alter_product_n_descarga_alter_product_pos_descarga_and_more'),
        ('my_library', '0002_alter_mybuyedproducts_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('precio', models.FloatField(blank=True)),
                ('producto', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pixelsaurapp.product')),
            ],
        ),
    ]
